### ISSUE TITLE
MPV error on Launch

### ISSUE THREAD

**Issue by drewauff** [trianglecirclexyz/cthulhu#1]
I am on MacOS and have had mpv installed and working for a long time.

When I run cthulhu, it spits out an error indicating I do not have mpv installed.

note: In actual fact I have mpv and a MacOS fork of mpv that basically makes mpv a gui app on a mac. Both work perfectly.

**Comment by drewauff** [comment]
I fixed, just had to edit the path inside the code to match the location on mpv. Works well.

I have some suggestions:

- Allow hitting esc to exit
- More categories, Tv Shows, music etc. they only show when using the --fast switch
- Add a config file
- Add a switch to allow for custom number of results or 
- Add support for fzf (just a thought), this would allow for "unlimited" search results
- Add columns for peers, leeches etc.
- Add more urls/sites (the more the better)

I do think that using a config file would allow for a lot more customising.

Keep up the awesome work.

-
Andy

**Comment by trianglecirclexyz** [comment]
It's nice that you found a fix so fast, I was worried for a second there since I didn't officially test on macOS yet (oops). 

Also, thanks for the suggestions! I will definitely look into including most of them depending on the viability. Stuff like a config file and more URL sources are already being planned for (I'm looking to organize the code a bit better first since it's a bit of a mess right now). 

An option to customize the number of results is trivial to add for anything less than 20. It's also technically possible to add an option to show more than 20 results, but it would require making more requests since each search on 1337x is limited to 20 per page. I'll still look into it since that's what the default filter does anyways.

Raiyan

**Comment by Kabouik** [comment]
> I fixed, just had to edit the path inside the code to match the location on mpv. Works well.

Just curious, would `master` correctly detect your `mpv` executable on MacOS? The dependency check is no longer based on hardcoded paths, hopefully this should work on MacOS too now.

**Comment by drewauff** [comment]
hmmm, not to sure about that, as the app I use is in /Applications rather than /usr/local/bin etc.

I have just come across webtorrent-cli and and straight away thought of your app. Might be worth it for you to have a look at the flags they have included
for some inspiration ie. --stdout so you can output to a custom client or wherever.

Another program you may want to look at is pirate-get, its essential a torrent searcher & downloader, but unlike yours it searches multiple sites at once.
webtorrent-cli and pirate-get are similar with the exception that webtorrent-cli needs a magnet file or a direct link whereas pirate-get does not, you have have to select from a (possibly huge) list and select to download with whatever client you want.

Just some food for thought.

To me it just seems that a hybrid of the 3 projects would be perfect:

- Cthulhu's streaming capablilites (granted webtorrent-cli can stream like yours does just with more options in the streaming department.)
- webtorrent-cli's customisation
- pirate-get's torrent searching capabilities.

I hope this helps you in some way
-
Andy

**Comment by Kabouik** [comment]
Just to disambiguate, I am not the developer of `cthulhu`, but I know it no longer checks for hardcoded paths to detect mpv, so it may work for you out of the box. I am not sure how `PATH` is handled on MacOS though. That's why I was curious about whether master would work on your end.

@trianglecirclexyz knows about `webtorrent-cli` but while there are common features with `peerflix`, there are also a few differences. They seem to both have their strengths but apparently should be relatively easily interchangeable.

I knew about `pirate-get` and tended to use it together with `stig` (a TUI torrent application based on `transmission`), but I admit I like the straightforward use of `cthulhu` where you don't even have to copy a magnet. I use it on my phone so not having to deal with the clipboard is more comfortable.

If you want to try something like `cthulhu` but using `webtorrent` under the hood, have a look `notflix` which was apparently an inspiration for `cthulhu` (the link is in the README here).

**Comment by trianglecirclexyz** [comment]
I think it depends on how mpv/vlc are installed on macOS for it to work out of the box from my testing in a mac VM. Im planning on writing a seperate bit for macOS/BSD installation after some more testing.

**Comment by drewauff** [comment]
looks like notflix depends on x11?

warning: no locale support
cannot open display

**Comment by Kabouik** [comment]
Probably when using dmenu indeed, which is the default, but someone submitted a PR to allo full use from the CLI and therefore making dmenu optional. I haven't tried though.
